modLoader="javafml"
loaderVersion="[40,)"
license="CC-BY-NC-SA"

[[mods]]
modId="industry"
version="0.0.2"
displayName="changed plus:Industry"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="耿悠博, MCreator"

[[dependencies.industry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.industry]]
    modId="changed"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.industry]]
    modId="create"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

